### ISSUE TITLE
PA: Playing songs with progress bar with continuous play

### ISSUE THREAD

**Issue by therealmeyer** [therealmeyer/SonicStratus#4] opened 2018-06-14 15:39 UTC
- [ ] Users can navigate through site with continuous music playing
- [ ] User can skip ahead in songs
- [ ] Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds to demonstrate the feature

**Comment by therealmeyer** [comment] 2018-06-14 15:41
I had a lot of trouble styling my slider. Still haven'y gotten it quite right. The click and the slider are a bit off. You can seek through waveform if waveform and player are in sync and on same page.

**Comment by AAlfarho** [comment] 2018-06-14 17:39
Great job ont he media playback, we achieved continuous playback while navigating through the site. There are a couple of details we need to address before moving forward.

- [ ] When navigating through the site the waveform and the player un-sync each other. In this case I think the issue is the fact that every time we visit the `/stream` route we reload the whole waveform.
![screen shot 2018-06-14 at 10 06 56 am](https://user-images.githubusercontent.com/1103663/41427142-ccd258e4-6fba-11e8-8b11-f69f00c7d427.png)
- [x]  Hovering over the volume pops the volume slide bar, thats great, however, clicking on the speaker/volume icon should mute the audio.
![screen shot 2018-06-14 at 10 13 30 am](https://user-images.githubusercontent.com/1103663/41427528-11ebfbb4-6fbc-11e8-963f-ba05b8ccc8f7.png)
- [x] We should not have dummy buttons that have no action, in this case your forward and previous buttons on the media player bar dont have any actions, what should we do with these ones?

Feel free to check the items on this list and assign this issue back to me once the mentioned points are addressed.

**On a side note, I liked your music selection :) .**

**Comment by therealmeyer** [comment] 2018-06-14 18:13
Hey Andres, I have no idea on how to sync up the waveform and the player when changing pages. It was something that I wanted to ask you about. I have been trying, and trying to think of different solutions but have been struggling. Fixed other issues though.

**Comment by AAlfarho** [comment] 2018-06-14 21:34
As discussed assign this issue back to me, once the user issue is addressed, that way i can go through the whole site checking its overall functionality.

**Comment by AAlfarho** [comment] 2018-06-15 00:12
Good job.

This MVP is now complete!

**Closed as completed by AAlfarho** 2018-06-15 00:12 UTC
Labels: core feature
